/**
 * SkinHubApp API
 * A Skin Cream, Soap and Beauty Analysis Forum
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LoginDto {
    username?: string;
    emailAddress?: string;
    password?: string;
}
